plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
}

group = 'info.preva1l'
version = "2.7.2"

allprojects {
    apply plugin: 'com.gradleup.shadow'
    apply plugin: 'maven-publish'
    apply plugin: 'java'

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(21))
    }

    compileJava.options.encoding = 'UTF-8'
    javadoc.options.encoding = 'UTF-8'
    javadoc.options.addStringOption('Xdoclint:none', '-quiet')

    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        compileOnly 'org.jetbrains:annotations:26.1.0'
        compileOnly 'org.projectlombok:lombok:1.18.42'
        annotationProcessor 'org.projectlombok:lombok:1.18.42'
        annotationProcessor 'org.jetbrains:annotations:24.0.0'

        testImplementation(platform('org.junit:junit-bom:5.14.0'))
        testImplementation('org.junit.jupiter:junit-jupiter')
        testRuntimeOnly('org.junit.platform:junit-platform-launcher')

        testCompileOnly 'org.jetbrains:annotations:26.1.0'
        testCompileOnly 'org.projectlombok:lombok:1.18.42'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.42'
    }

    test {
        useJUnitPlatform()
        testLogging {
            events "passed", "skipped", "failed"
        }
        failOnNoDiscoveredTests = false
    }

    processResources {
        def props = [version: rootProject.version]
        inputs.properties props
        filteringCharset = 'UTF-8'
        filesMatching('plugin.yml') {
            expand props
        }
    }
}

subprojects {
    version = rootProject.version

    shadowJar {
        destinationDirectory.set(file("$rootDir/target"))
        archiveBaseName.set("${rootProject.name}-${project.name.capitalize()}")
        archiveClassifier.set('')
        //minimize()
    }

    task sourceJar(type: Jar) {
        from sourceSets.main.allSource
        archiveClassifier.set('sources')
    }

    task javadocJar(type: Jar) {
        from javadoc
        archiveClassifier.set('javadoc')
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifact shadowJar
                artifact(tasks.named('sourceJar'))
                artifact(tasks.named('javadocJar'))
            }
        }
    }

    jar.dependsOn shadowJar
    clean.delete "$rootDir/target"
}

logger.lifecycle("Building Fadah ${version}")